[build]
command = "npm run build"


[build.processing]
skip_processing = true
[[headers]]
for = "/*.gif"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "image/gif"